apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 3
  template:
    metadata:
      labels:
        app: alpine
        running: afterLabels
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ['sh', '-c', 'sleep 60 && shutdown -r now']
