AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: newMailReader.main
      Runtime: Python3.7
      Code: 's3://blue-pigeos/myProjects/python/newMailReader.py'
