AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: newMailReader.main
      Runtime: python3.6
      CodeUri: s3://blue-pigeons/myProjects/python/zip/newMailReader.zip